use std::cell::Cell;
use std::fmt::Write as _;
use std::io;
use std::time::Duration;

use agentdp_crypto::test_support::{tls_client_config_with_root_pem, tls_server_config_from_pem};
use agentdp_crypto::{
    CertificateAuthorityPem, TlsCiphertextRead, TlsClientSession, TlsPlaintextRead, TlsPlaintextWrite, TlsServerConfig,
    TlsServerSession,
};

use super::super::{
    DriveBudget, DriveGuestProgress, Error, Result, Simulator, SmolTcpGuest, SteppedNetwork, TcpHandle,
};

const PROTOCOL_DRIVE_BUDGET: DriveBudget = DriveBudget {
    max_steps: 4096,
    step_time: Duration::from_millis(1),
};
const CLIENT_TLS_FEED_CHUNK_BYTES: usize = 16 * 1024;

// Test-only TLS material generated by `generate-network-test-tls-fixtures`.
const MEDIATED_CA_CERT_PEM: &str = include_str!(".generated/mediated-ca.cert.pem");
const MEDIATED_CA_KEY_PEM: &str = include_str!(".generated/mediated-ca.key.pem");
const UPSTREAM_CA_CERT_PEM: &str = include_str!(".generated/upstream-ca.cert.pem");
const UPSTREAM_SERVER_CERT_PEM: &str = include_str!(".generated/upstream-server.cert.pem");
const UPSTREAM_SERVER_KEY_PEM: &str = include_str!(".generated/upstream-server.key.pem");

pub(crate) struct TestTlsIdentity {
    pub(crate) root_ca_pem: String,
    pub(crate) server_config: TlsServerConfig,
}

pub(crate) fn fixed_mediated_ca() -> CertificateAuthorityPem {
    CertificateAuthorityPem {
        cert_pem: MEDIATED_CA_CERT_PEM.to_owned(),
        key_pem: MEDIATED_CA_KEY_PEM.to_owned(),
    }
}

impl TestTlsIdentity {
    pub(crate) fn fixed_upstream() -> Result<Self> {
        let server_config = tls_server_config_from_pem(UPSTREAM_SERVER_CERT_PEM, UPSTREAM_SERVER_KEY_PEM)
            .map_err(|error| Error::from_display("server TLS config", error))?;
        Ok(Self {
            root_ca_pem: UPSTREAM_CA_CERT_PEM.to_owned(),
            server_config,
        })
    }
}

pub(crate) fn client_tls(host: &str, ca_pem: &str) -> Result<TlsClientSession> {
    let config = tls_client_config_with_root_pem(ca_pem)
        .map_err(|error| Error::from_display("create TLS client config", error))?;
    TlsClientSession::connect(&config, host).map_err(|error| Error::from_display("client TLS", error))
}

pub(crate) fn drive_tls_until<N>(
    sim: &mut Simulator,
    guest: &mut SmolTcpGuest,
    running: &mut N,
    tcp: TcpHandle,
    tls: &mut TlsClientSession,
    label: &str,
    mut done: impl FnMut(&TlsClientSession, &[u8]) -> bool,
) -> Result<Vec<u8>>
where
    N: SteppedNetwork,
{
    let mut plaintext = Vec::new();
    let tls_bytes_flushed = Cell::new(0_usize);
    let plaintext_len = Cell::new(0_usize);
    let tls_handshaking = Cell::new(tls.is_handshaking());
    let progress = Cell::new(0_usize);
    sim.drive_guest_until_with_progress(
        guest,
        running,
        DriveGuestProgress {
            label,
            budget: PROTOCOL_DRIVE_BUDGET,
        },
        |guest, running| {
            let io = drive_client_tls_io(guest, running, tcp, tls, &mut plaintext)?;
            tls_bytes_flushed.set(tls_bytes_flushed.get().saturating_add(io.flushed));
            plaintext_len.set(plaintext.len());
            tls_handshaking.set(tls.is_handshaking());
            progress.set(tls_bytes_flushed.get().saturating_add(plaintext_len.get()));
            Ok(done(tls, &plaintext))
        },
        || progress.get(),
        |output| {
            let _ = writeln!(output, "  phase: {label}");
            let _ = writeln!(output, "  client_tls_bytes_flushed: {}", tls_bytes_flushed.get());
            let _ = writeln!(output, "  client_plaintext_bytes_read: {}", plaintext_len.get());
            let _ = writeln!(output, "  tls_handshaking: {}", tls_handshaking.get());
        },
    )?;
    Ok(plaintext)
}

pub(crate) fn flush_client_tls<N>(
    guest: &mut SmolTcpGuest,
    running: &mut N,
    tcp: TcpHandle,
    tls: &mut TlsClientSession,
) -> Result<usize>
where
    N: SteppedNetwork,
{
    let mut flushed = 0_usize;
    loop {
        let mut output = Vec::new();
        tls.drain_ciphertext_to(&mut output)
            .map_err(|error| Error::from_display("write client TLS", error))?;
        if output.is_empty() {
            return Ok(flushed);
        }
        flushed += output.len();
        guest.write_all(running, tcp, &output)?;
    }
}

#[derive(Debug, Clone, Copy, Default)]
pub(crate) struct ClientTlsIo {
    pub(crate) flushed: usize,
    pub(crate) ciphertext_read: usize,
}

pub(crate) fn drive_client_tls_io<N>(
    guest: &mut SmolTcpGuest,
    running: &mut N,
    tcp: TcpHandle,
    tls: &mut TlsClientSession,
    plaintext: &mut Vec<u8>,
) -> Result<ClientTlsIo>
where
    N: SteppedNetwork,
{
    let flushed = flush_client_tls(guest, running, tcp, tls)?;
    let incoming = guest.read_available_bytes(tcp)?;
    let ciphertext_read = incoming.len();
    if !incoming.is_empty() {
        feed_client_ciphertext_and_drain_plaintext(tls, &incoming, plaintext)?;
    }
    Ok(ClientTlsIo {
        flushed,
        ciphertext_read,
    })
}

fn feed_client_ciphertext_and_drain_plaintext(
    tls: &mut TlsClientSession,
    bytes: &[u8],
    plaintext: &mut Vec<u8>,
) -> Result<()> {
    let mut input = bytes;
    while !input.is_empty() {
        match tls
            .read_ciphertext_bounded(&mut input, CLIENT_TLS_FEED_CHUNK_BYTES)
            .map_err(|error| Error::from_display("read client TLS", error))?
        {
            TlsCiphertextRead::Read(_read) => {}
            TlsCiphertextRead::Blocked => {
                return Err(Error::new("client TLS blocked while consuming in-memory ciphertext"));
            }
            TlsCiphertextRead::Closed => return Err(Error::new("client TLS closed while feeding ciphertext")),
        }
        drain_client_plaintext(tls, plaintext)?;
    }
    Ok(())
}

fn drain_client_plaintext(tls: &mut TlsClientSession, output: &mut Vec<u8>) -> Result<()> {
    let mut buffer = [0_u8; 4096];
    loop {
        match tls.read_plaintext_some(&mut buffer) {
            Ok(TlsPlaintextRead::Plaintext(read)) => output.extend_from_slice(&buffer[..read]),
            Ok(TlsPlaintextRead::Blocked | TlsPlaintextRead::Closed) => return Ok(()),
            Err(error) => return Err(Error::from_display("read client plaintext", error)),
        }
    }
}

pub(crate) fn feed_server_tls(tls: &mut TlsServerSession, bytes: &[u8]) -> io::Result<()> {
    let mut input = bytes;
    while !input.is_empty() {
        match tls.accept_ciphertext_bounded(input)? {
            TlsCiphertextRead::Read(read) => input = &input[read..],
            TlsCiphertextRead::Blocked => {
                return Err(io::Error::new(
                    io::ErrorKind::WouldBlock,
                    "server TLS blocked while consuming in-memory ciphertext",
                ));
            }
            TlsCiphertextRead::Closed => return Err(io::ErrorKind::UnexpectedEof.into()),
        }
    }
    Ok(())
}

pub(crate) fn read_plaintext_into(tls: &mut TlsServerSession, output: &mut Vec<u8>) -> io::Result<()> {
    let mut buffer = [0_u8; 4096];
    loop {
        match tls.read_plaintext_some(&mut buffer) {
            Ok(TlsPlaintextRead::Plaintext(read)) => output.extend_from_slice(&buffer[..read]),
            Ok(TlsPlaintextRead::Blocked | TlsPlaintextRead::Closed) => return Ok(()),
            Err(error) => return Err(error),
        }
    }
}

pub(crate) fn flush_server_tls(tls: &mut TlsServerSession, output: &mut Vec<u8>) -> io::Result<()> {
    let _drain = tls.drain_ciphertext_to(output)?;
    Ok(())
}

pub(crate) fn write_client_plaintext_limited(
    tls: &mut TlsClientSession,
    plaintext: &[u8],
    written: &mut usize,
    write_limit: usize,
) -> Result<()> {
    let limit = (*written).saturating_add(write_limit.max(1)).min(plaintext.len());
    while *written < limit {
        match tls
            .write_plaintext_some(&plaintext[*written..limit])
            .map_err(|error| Error::from_display("write TLS plaintext", error))?
        {
            TlsPlaintextWrite::Accepted(0) => return Err(Error::new("client TLS accepted zero plaintext bytes")),
            TlsPlaintextWrite::Accepted(accepted) => *written += accepted,
            TlsPlaintextWrite::BlockedByPendingCiphertext => return Ok(()),
        }
    }
    Ok(())
}

pub(crate) fn write_server_plaintext(
    tls: &mut TlsServerSession,
    plaintext: &[u8],
    output: &mut Vec<u8>,
) -> io::Result<usize> {
    let mut offset = 0_usize;
    while offset < plaintext.len() {
        match tls.write_plaintext_some(&plaintext[offset..])? {
            TlsPlaintextWrite::Accepted(0) => {
                return Err(io::Error::new(
                    io::ErrorKind::WriteZero,
                    "server TLS accepted zero plaintext bytes",
                ));
            }
            TlsPlaintextWrite::Accepted(written) => {
                offset = offset.saturating_add(written);
                flush_server_tls(tls, output)?;
            }
            TlsPlaintextWrite::BlockedByPendingCiphertext => flush_server_tls(tls, output)?,
        }
    }
    flush_server_tls(tls, output)?;
    Ok(offset)
}
